services:
  user-service:
    build: ./user-service
    ports:
      - "3004:3004"
    environment:
      - PORT=3004

  account-service:
    build: ./account-service
    ports:
      - "3003:3003"
    environment:
       - PORT=3003

  notification-service:
    build: ./notification-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002

  transaction-service:
    build: ./transaction-service
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - ACCOUNT_URL=http://account-service:3003/accounts
      - NOTIFICATION_URL=http://notification-service:3002/notify

  bigbank:
    build: ./bigbank
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - USER_URL=http://user-service:3004/users
      - ACCOUNT_URL=http://account-service:3003/accounts
      - NOTIFICATION_URL=http://notification-service:3002/notify
    depends_on:
      - user-service
      - account-service
      - notification-service

  bigbank-admin:
    build: ./bigbank-admin
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - USER_URL=http://user-service:3004/users
      - ACCOUNT_URL=http://account-service:3003/accounts
      - TRANSACTION_URL=http://transaction-service:3005/transactions
    depends_on:
      - user-service
      - account-service
      - transaction-service

  frontend:
    build: ./frontend
    ports:
      - 8080:80
    depends_on:
      - bigbank
